In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("hotel_bookings.csv")
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [36]:
## Dataset Overview

##Understanding the structure, number of columns, and data types.




original_data = pd.read_csv("hotel_bookings.csv")
original_data.shape

(119390, 32)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

In [5]:
df.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,103050.000000,6797.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.370416,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.103890,0.007949,0.031912,0.087118,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363
std,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.398561,0.097436,0.175767,0.844336,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,0.000000,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,179.000000,0.000000,94.575000,0.000000,0.000000
75%,1.000000,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,229.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000

In [6]:
## Handling Missing Values

##Several columns contain missing values which need to be treated before analysis.

In [7]:
df.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [8]:
df['children'] = df['children'].fillna(0)
df['country'] = df['country'].fillna("Unknown")
df['agent'] = df['agent'].fillna(0)

# drop company column because it has too many missing values
df = df.drop(columns=['company'])

In [9]:
## Removing Duplicate Rows

##Duplicate booking records can distort analysis and must be removed.

In [10]:
df.duplicated().sum()

np.int64(32001)

In [11]:
df = df.drop_duplicates()

In [12]:
## Treating Outliers in Average Daily Rate (ADR)

##Extreme ADR values can distort analysis and need to be removed.

In [13]:
df['adr'].describe()

count    87389.000000
mean       106.339070
std         55.013097
min         -6.380000
25%         72.000000
50%         98.100000
75%        134.000000
max       5400.000000
Name: adr, dtype: float64

In [14]:
df = df[df['adr'] < 500]

In [15]:
## Feature Engineering

##New features are created to improve analytical insights.

In [16]:
df['total_stay'] = df['stays_in_weekend_nights'] + df['stays_in_week_nights']

In [17]:
df['total_guests'] = df['adults'] + df['children'] + df['babies']

In [18]:
df['total_revenue'] = df['adr'] * df['total_stay']

In [19]:
df['reservation_status_date'] = pd.to_datetime(df['reservation_status_date'])

In [20]:
##Final Dataset Check

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 87386 entries, 0 to 119389
Data columns (total 34 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           87386 non-null  object
 1   is_canceled                     87386 non-null  int64
 2   lead_time                       87386 non-null  int64
 3   arrival_date_year               87386 non-null  int64
 4   arrival_date_month              87386 non-null  object
 5   arrival_date_week_number        87386 non-null  int64
 6   arrival_date_day_of_month       87386 non-null  int64
 7   stays_in_weekend_nights         87386 non-null  int64
 8   stays_in_week_nights            87386 non-null  int64
 9   adults                          87386 non-null  int64
 10  children                        87386 non-null  float64
 11  babies                          87386 non-null  int64
 12  meal                            87386 non-null  object
 13  country                         87386 non-null  object
 14  market_segment                  87386 non-null  object
 15  distribution_channel            87386 non-null  object
 16  is_repeated_guest               87386 non-null  int64
 17  previous_cancellations          87386 non-null  int64
 18  previous_bookings_not_canceled  87386 non-null  int64
 19  reserved_room_type              87386 non-null  object
 20  assigned_room_type              87386 non-null  object
 21  booking_changes                 87386 non-null  int64
 22  deposit_type                    87386 non-null  object
 23  agent                           87386 non-null  float64
 24  days_in_waiting_list            87386 non-null  int64
 25  customer_type                   87386 non-null  object
 26  adr                             87386 non-null  float64
 27  required_car_parking_spaces     87386 non-null  int64
 28  total_of_special_requests       87386 non-null  int64
 29  reservation_status              87386 non-null  object
 30  reservation_status_date         87386 non-null  datetime64[ns]
 31  total_stay                      87386 non-null  int64
 32  total_guests                    87386 non-null  float64
 33  total_revenue                   87386 non-null  float64
dtypes: datetime64[ns](1), float64(5), int64(17), object(11)
memory usage: 23.3+ MB

In [22]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,total_stay,total_guests,total_revenue
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,0,Transient,0.0,0,0,Check-Out,2015-07-01,0,2.0,0.0
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,0,Transient,0.0,0,0,Check-Out,2015-07-01,0,2.0,0.0
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,0,Transient,75.0,0,0,Check-Out,2015-07-02,1,1.0,75.0
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,0,Transient,75.0,0,0,Check-Out,2015-07-02,1,1.0,75.0
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,0,Transient,98.0,0,1,Check-Out,2015-07-03,2,2.0,196.0

In [25]:
df = df[(df['adults'] + df['children'] + df['babies']) > 0]

In [26]:
df.isnull().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
total_stay                        0
total_guests                      0
total_revenue                     0
dtype: int64

In [28]:
month_order = [
'January','February','March','April','May','June',
'July','August','September','October','November','December'
]

df['arrival_date_month'] = pd.Categorical(df['arrival_date_month'], categories=month_order, ordered=True)

In [30]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date', 'total_stay',
       'total_guests', 'total_revenue'],
      dtype='object')

In [31]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,total_stay,total_guests,total_revenue
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,0,Transient,0.0,0,0,Check-Out,2015-07-01,0,2.0,0.0
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,0,Transient,0.0,0,0,Check-Out,2015-07-01,0,2.0,0.0
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,0,Transient,75.0,0,0,Check-Out,2015-07-02,1,1.0,75.0
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,0,Transient,75.0,0,0,Check-Out,2015-07-02,1,1.0,75.0
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,0,Transient,98.0,0,1,Check-Out,2015-07-03,2,2.0,196.0

In [32]:
df.shape

(87220, 34)

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 87220 entries, 0 to 119389
Data columns (total 34 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           87220 non-null  object
 1   is_canceled                     87220 non-null  int64
 2   lead_time                       87220 non-null  int64
 3   arrival_date_year               87220 non-null  int64
 4   arrival_date_month              87220 non-null  category
 5   arrival_date_week_number        87220 non-null  int64
 6   arrival_date_day_of_month       87220 non-null  int64
 7   stays_in_weekend_nights         87220 non-null  int64
 8   stays_in_week_nights            87220 non-null  int64
 9   adults                          87220 non-null  int64
 10  children                        87220 non-null  float64
 11  babies                          87220 non-null  int64
 12  meal                            87220 non-null  object
 13  country                         87220 non-null  object
 14  market_segment                  87220 non-null  object
 15  distribution_channel            87220 non-null  object
 16  is_repeated_guest               87220 non-null  int64
 17  previous_cancellations          87220 non-null  int64
 18  previous_bookings_not_canceled  87220 non-null  int64
 19  reserved_room_type              87220 non-null  object
 20  assigned_room_type              87220 non-null  object
 21  booking_changes                 87220 non-null  int64
 22  deposit_type                    87220 non-null  object
 23  agent                           87220 non-null  float64
 24  days_in_waiting_list            87220 non-null  int64
 25  customer_type                   87220 non-null  object
 26  adr                             87220 non-null  float64
 27  required_car_parking_spaces     87220 non-null  int64
 28  total_of_special_requests       87220 non-null  int64
 29  reservation_status              87220 non-null  object
 30  reservation_status_date         87220 non-null  datetime64[ns]
 31  total_stay                      87220 non-null  int64
 32  total_guests                    87220 non-null  float64
 33  total_revenue                   87220 non-null  float64
dtypes: category(1), datetime64[ns](1), float64(5), int64(17), object(10)
memory usage: 22.7+ MB

In [42]:
df.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,...,booking_changes,agent,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,reservation_status_date,total_stay,total_guests,total_revenue
count,87220.000000,87220.000000,87220.000000,87220.000000,87220.000000,87220.000000,87220.000000,87220.000000,87220.000000,87220.000000,...,87220.000000,87220.000000,87220.000000,87220.000000,87220.000000,87220.000000,87220,87220.000000,87220.000000,87220.000000
mean,0.275258,79.979202,2016.210376,26.834740,15.815971,1.004701,2.624134,1.879420,0.138913,0.010846,...,0.268516,81.093637,0.746377,106.449952,0.084304,0.698980,2016-08-31 03:01:35.592753920,3.628835,2.029179,394.916168
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,-6.380000,0.000000,0.000000,2014-10-17 00:00:00,0.000000,1.000000,-63.800000
25%,0.000000,11.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,...,0.000000,9.000000,0.000000,72.250000,0.000000,0.000000,2016-03-18 00:00:00,2.000000,2.000000,153.000000
50%,0.000000,49.000000,2016.000000,27.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,...,0.000000,9.000000,0.000000,98.190000,0.000000,0.000000,2016-09-08 00:00:00,3.000000,2.000000,299.200000
75%,1.000000,125.000000,2017.000000,37.000000,23.000000,2.000000,4.000000,2.000000,0.000000,0.000000,...,0.000000,240.000000,0.000000,134.100000,0.000000,1.000000,2017-03-05 00:00:00,5.000000,2.000000,504.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,...,18.000000,535.000000,391.000000,451.500000,8.000000,5.000000,2017-09-14 00:00:00,69.000000,55.000000,7590.000000
std,0.446647,86.060132,0.686049,13.669122,8.835710,1.027422,2.039849,0.621716,0.456289,0.113710,...,0.710664,109.979423,10.001571,51.846541,0.281656,0.832059,NaN,2.742961,0.790140,369.068453

In [43]:
## Data Cleaning Summary


#  Filled missing values in children, country, and agent
#  Dropped company column due to excessive missing values
#  Removed duplicate booking records
#  Treated extreme ADR outliers
#  Created new features : total_stay, total_guests, total_revenue
#  Converted reservation_status_date to datetime format

## Final dataset size : 87220 rows and 34 columns